# Data Processing Configuration
data:
  raw_path: "data/raw"
  processed_path: "data/processed"
  features_path: "data/processed/features"
  dataset_name: "singhnavjot2062001/11000-medicine-details"

# Model Configuration
models:
  random_forest:
    n_estimators_range: [50, 500]
    max_depth_range: [3, 20]
    min_samples_split_range: [2, 10]
    random_state: 42
    
  gradient_boosting:
    n_estimators_range: [50, 500]
    max_depth_range: [3, 15]
    learning_rate_range: [0.01, 0.3]
    random_state: 42
    
  svr:
    C_range: [0.1, 20.0]
    epsilon_range: [0.01, 1.0]
    gamma_range: [0.001, 1.0]
    kernels: ["rbf", "linear", "poly"]

# Feature Engineering
features:
  text_features:
    - Salt_Composition
    - Uses
    - Side_Effects
  categorical_features:
    - Manufacturer
  review_features:
    - Review_Excellent
    - Review_Average
    - Review_Poor

# Visualization Settings
visualization:
  style: "seaborn"
  figure_size: [12, 8]
  color_scheme: "Set3"
  dpi: 300

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_path: "logs/medicine_analysis.log"
