services:
  - type: web
    name: medipredictpro
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run src/app.py
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11