name: MediPredictPro CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Deploy to Render
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      run: |
        echo "Starting deployment to Render..."
        curl -X POST "https://api.render.com/deploy/prj-ctvrla0gph6c73cf8ol0?key=${{ secrets.RENDER_API_KEY }}"
        echo "Deployment triggered successfully"